version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: supermarket
    volumes:
      - pgdata:/var/lib/postgresql/data

  online-platform:
    build:
      context: ./Online shopping
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: supermarket
      DB_PORT: 5432

  offline-system:
    build:
      context: ./src
      dockerfile: Dockerfile.python
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_NAME: supermarket
      DB_PORT: 5432
      MOCK_HARDWARE: "true"

volumes:
  pgdata: