version: '3.8'

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  online-platform:
    build: 
      context: ./online-platform
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "80:5000"
    depends_on:
      - db

  offline-system:
    build: 
      context: ./offline-system
      dockerfile: Dockerfile
    privileged: true
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/gpiomem:/dev/gpiomem"
    env_file: .env
    depends_on:
      - online-platform

volumes:
  pgdata: