# Use official AMD64 Python image
FROM arm32v7/python:3.9-slim-bullseye

WORKDIR /app

# Install only essential dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    libzbar0 \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

CMD ["python", "main_ai.py"]